version: 2.1

jobs:
  build-and-test-project1:
    working_directory: ~/my-monorepo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install-deps
      - run:
          name: Run Cypress Tests for Project 1
          command: yarn workspace project1 cypress run

  build-and-test-project2:
    working_directory: ~/my-monorepo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install-deps
      - run:
          name: Run Cypress Tests for Project 2
          command: yarn workspace project2 cypress run

workflows:
  version: 2
  build:
    jobs:
      - build-and-test-project1
      - build-and-test-project2
