version: 2.1

parameters:
  param1:
    type: string

workflows:
  version: 2
  continue:
    jobs:
      - run-cypress-project1

jobs:
  run-cypress-project1:
    executor: default
    steps:
      - checkout
      - run:
          name: Install Dependencies for Project 1
          command: yarn install
      - run:
          name: Run Cypress Tests for Project 1
          command: yarn workspace project1 cypress run --param1=$param1
