version: 2.1

parameters:
  param1:
    type: string

workflows:
  version: 2
  continue:
    jobs:
      - run-cypress-project2

jobs:
  run-cypress-project2:
    executor: default
    steps:
      - checkout
      - run:
          name: Install Dependencies for Project 2
          command: yarn install
      - run:
          name: Run Cypress Tests for Project 2
          command: yarn workspace project2 cypress run --param1=$param1
