name: Cypress Tests

on:
  push:
    branches:
      - master  

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.1

      - name: Install Dependencies
        run: yarn install

      - name: Debug Workspace
        run: |
          pwd  # Print the current directory
          ls   # List the contents of the current directory


      # - name: Run Cypress Tests for Project 1
      #   run: yarn workspace project1 cypress run
